// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.10.0
// source: pkg/proto/algorithms/algorithms.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_algorithms_algorithms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_algorithms_algorithms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_algorithms_algorithms_proto_rawDescGZIP(), []int{0}
}

var File_pkg_proto_algorithms_algorithms_proto protoreflect.FileDescriptor

var file_pkg_proto_algorithms_algorithms_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6c, 0x67, 0x6f,
	0x72, 0x69, 0x74, 0x68, 0x6d, 0x73, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a,
	0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x6b, 0x0a,
	0x0a, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x73, 0x12, 0x5d, 0x0a, 0x0a, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x22, 0x1a, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2f, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x2d, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x3a, 0x01, 0x2a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_proto_algorithms_algorithms_proto_rawDescOnce sync.Once
	file_pkg_proto_algorithms_algorithms_proto_rawDescData = file_pkg_proto_algorithms_algorithms_proto_rawDesc
)

func file_pkg_proto_algorithms_algorithms_proto_rawDescGZIP() []byte {
	file_pkg_proto_algorithms_algorithms_proto_rawDescOnce.Do(func() {
		file_pkg_proto_algorithms_algorithms_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_algorithms_algorithms_proto_rawDescData)
	})
	return file_pkg_proto_algorithms_algorithms_proto_rawDescData
}

var file_pkg_proto_algorithms_algorithms_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_algorithms_algorithms_proto_goTypes = []interface{}{
	(*EmptyMessage)(nil), // 0: proto.EmptyMessage
}
var file_pkg_proto_algorithms_algorithms_proto_depIdxs = []int32{
	0, // 0: proto.Algorithms.HelloWorld:input_type -> proto.EmptyMessage
	0, // 1: proto.Algorithms.HelloWorld:output_type -> proto.EmptyMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_algorithms_algorithms_proto_init() }
func file_pkg_proto_algorithms_algorithms_proto_init() {
	if File_pkg_proto_algorithms_algorithms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_algorithms_algorithms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_algorithms_algorithms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_algorithms_algorithms_proto_goTypes,
		DependencyIndexes: file_pkg_proto_algorithms_algorithms_proto_depIdxs,
		MessageInfos:      file_pkg_proto_algorithms_algorithms_proto_msgTypes,
	}.Build()
	File_pkg_proto_algorithms_algorithms_proto = out.File
	file_pkg_proto_algorithms_algorithms_proto_rawDesc = nil
	file_pkg_proto_algorithms_algorithms_proto_goTypes = nil
	file_pkg_proto_algorithms_algorithms_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AlgorithmsClient is the client API for Algorithms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlgorithmsClient interface {
	HelloWorld(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type algorithmsClient struct {
	cc grpc.ClientConnInterface
}

func NewAlgorithmsClient(cc grpc.ClientConnInterface) AlgorithmsClient {
	return &algorithmsClient{cc}
}

func (c *algorithmsClient) HelloWorld(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/proto.Algorithms/HelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlgorithmsServer is the server API for Algorithms service.
type AlgorithmsServer interface {
	HelloWorld(context.Context, *EmptyMessage) (*EmptyMessage, error)
}

// UnimplementedAlgorithmsServer can be embedded to have forward compatible implementations.
type UnimplementedAlgorithmsServer struct {
}

func (*UnimplementedAlgorithmsServer) HelloWorld(context.Context, *EmptyMessage) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}

func RegisterAlgorithmsServer(s *grpc.Server, srv AlgorithmsServer) {
	s.RegisterService(&_Algorithms_serviceDesc, srv)
}

func _Algorithms_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmsServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Algorithms/HelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmsServer).HelloWorld(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Algorithms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Algorithms",
	HandlerType: (*AlgorithmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _Algorithms_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/algorithms/algorithms.proto",
}
